# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

if Book.count == 0
  
  b1 = Book.create(cover: "http://ecx.images-amazon.com/images/I/61obi3hJ9qL._SY344_BO1,204,203,200_.jpg", author: "H. B. Cushman", title: "History of the Choctaw, Chickasaw and Natchez Indians", passage: "Among the many and various questions that were asked of the different members of the delegation was the question, How they became so distinguished among their people? To which various answers were given, each telling his own story of the exploits which brought him out of obscurity and placed his name in the temple of human fame. Apushamatahah, up to this time, had said nothing. At length President Jackson requested the interpreter to ask him how he became such a great warrior and renowned chief. To which Apushamatahah coolly and with unassumed indifference replied: \"Tell the white chief it's none of his business.\" This unexpected retort attracted the attention of all present and all eyes were at once turned upon the bold chief. Jackson amused at the reply and pleased at the manly independence of the noble chief requested the interpreter to propound the same question again; which was done but to which Apushamatahah seemed to give no heed. The curiosity of all being greatly excited, the question was asked still again. To which Apushamatahah replied: \"Well, if the white chief must know, tell him that Apushamatahahubih has neither father nor mother, nor kinsman upon the earth. Tell him that once upon a time, far away from here in the great forests of the Choctaw Nation, a dark cloud arose from the western horizon, and with astonishing velocity, traveled up the arched expanse. In silence profound, all animate nature stood apart; soon the fearful cloud reached the zenith, then as quickly spread its dark mantle o'er the sky entire, shutting out the light of the sun, and wrapping earth in midnight gloom. Then burst the cloud and rose the wind; and while falling rains and howling winds, lightnings gleam and thunders roar, in wild confusion blended, a blinding flash blazed athwart the sky, then hurled its strength against a mighty oak and cleft it in equal twain from utmost top to lowest bottom; when, lo! from its riven trunk leaped a mighty man; in stature, perfect; in wisdom, profound; in bravery, unequalled-- a full-fledged warrior. 'Twas Apushamatahahubih.")
  
  b2 = Book.create(cover: "http://d.gr-assets.com/books/1387703741l/551211.jpg", author: "Robert Ringer", title: "Looking Out for #1", passage: "I've never paid much attention to so-called world-peace crusades. This is probably due to the fact that, in my lifetime- notwithstanding the increased efforts of \"world-peace\" movements- hostility and war among nations has continued to increase. What I'd never stopped to think about, however, was the reason there had always been war and why world peace was seemingly unattainable.
The problem is the mixing of the Definition Game with a little bit (or lots) of absolute morality. One guy's definition of world peace is to be left alone on his ranch. Another man's idea of world peace is forcibly splitting up the first fellow's ranch into a thousand plots and giving them away to those he deems to be in need of them. As long as these two men hold such incompatible views, the chances for peace are about as great as the odds against governments' putting an end to taxation. 
World-peace movements don't work for the same reason that laws intended to regulate emotions don't work. You can't unilaterally decide what constitutes world peace, then go around cramming it down everyone's throat. The cause the would-be crusader for world peace really is espousing is having four billion people accept his idea of what constitutes world peace. I don't like people deciding what's right, then trying to force me to accept it. My idea of world peace is everybody leaving everybody else alone- each man being free to live his life as he so desires and not interfering in the lives of others. My fear of peace crusaders is summed up in Eric Hoffer's statement, \"... when men league themselves mightily together to promote tolerance and peace on earth, they are likely to be violently intolerant toward those not of a like mind.\"
Don't be intimidated by idealistic abstract phrases like \"world peace.\" Everyone has a different idea of what it is, and there's no way that any group is going to get four billion people to agree to do anything- except through force. And forcing people to do things they don't want to do is not peace; it's something known as war.")

  b3 = Book.create(cover: "http://ecx.images-amazon.com/images/I/41GP3Y1FTYL.jpg", author: "Miguel De Cervantes Saavedra, John Rutherford (translation)", title: "Don Quixote (Penguin Classics)", passage: "As he was saying this he came to a crossroads, and this brought to his mind those other crossroads where knights errant would pause to consider which way to go; and, to imitate them, he remained motionless for a while; but after careful thought he let go of the reins, surrendering his will to that of his nag, which followed its original inclination- to head for its stable. After a couple of miles, Don Quixote spotted a throng of people who, as it afterwards transpired, were merchants from Toledo on their way to Murcia to buy silk. There were six of them, each beneath his sunshade, accompanied by four servants on horseback and three footmen. As soon as Don Quixote saw them, he imagined that here was the opportunity for a new adventure; and, wishing to imitate in every way he believed he could the passages of arms he'd read about in his books, he decided that one he had in mind was perfect for this situation. And so, with a gallant bearing and a resolute air, he steadied himself in his stirrups, clutched his lance, lifted his leather shield to his chest and, taking up his position in the middle of the highway, awaited the arrival of these knights errant, for this was what he judged them to be; and when they came within sight and earshot, Don Quixote raised his voice and, striking a haughty posture, declared:
\"You will none of you advance one step further unless all of you confess that in all the world there is no maiden more beauteous than the Empress of La Mancha, the peerless Dulcinea del Toboso.\"
The merchants halted when they heard these words and saw the strange figure uttering them, and from the figure and the words they realized that the man was mad; but they had a mind to stay and see what would be the outcome of the required confession and one of them, waggish and sharp-witted, said:
'Sir knight, we don't know who this worthy lady is; do let us see her, because if she's as beautiful as you claim she is, we'll most freely and willingly confess that what you say is true.'
'If I were to let you see her,' retorted Don Quixote, 'what merit would there be in confessing so manifest a truth? The whole point is that, without seeing her, you must believe, confess, affirm, swear and uphold it; if not, monstrous and arrogant wretches, you shall face me in battle forthwith. For whether you present yourselves one by one, as the order of chivalry requires, or all together, as is the custom and wicked practice of those of your ilk, here I stand and wait for you, confident in the justice of my cause.'
'Sir knight,' replied the merchant, 'I beg you, in the name of all us princes gathered here, that- so as not to burden our consciences by confessing something never seen or heard by any of us, particularly since it is so detrimental to the Empresses and Queens of La Alcarria and Extremadura- you be pleased to show us a portrait of that lady, even if no bigger than a grain of wheat; because the skein can be judged by the thread, as they say, and this will leave us satisfied and reassured, and leave you pleased and contented; indeed I believe we are already so far inclined in her favour that, even if her portrait shows that one of her eyes has gone skew-whiff and that sulphur and cinnabar ooze out of the other one, we will, just to please you, say in her favour whatever you want us to say.'
'It does not ooze, you infamous knaves,' replied Don Quixote, burning with anger. 'It does not ooze, I repeat, with what you say, but with ambergris and civet kept in finest cotton; and she is not skew-whiff or hunch-backed, but straighter than a Guadarrama spindle. And you shall pay for the great blasphemy you have uttered against such beauty as that of my lady!")

  b4 = Book.create(cover: "http://upload.wikimedia.org/wikipedia/en/7/7e/Demon-Haunted_World.jpg", author: "Carl Sagan", title: "The Demon Haunted World: Science as a Candle in the Dark", passage: "Education on the value of free speech and the other freedoms reserved by the Bill of Rights, about what happens when you don't have them, and about how to exercise and protect them, should be an essential prerequisite for being an American citizen- or indeed a citizen of any nation, the more so to the degree that such rights remain unprotected. If we can't think for ourselves, if we're unwilling to question authority, then we're just putty in the hands of those in power. But if the citizens are educated and form their own opinions, then those 
in power work for us. In every country, we should be teaching our children the scientific method and the reasons for a Bill of Rights. With it comes a certain decency, humility and community spirit. In the demon-haunted world that we inhabit by virtue of being human, this may be all that stands between us and the enveloping darkness.")

  b5 = Book.create(cover: "http://d.gr-assets.com/books/1366758096l/61535.jpg", author: "Richard Dawkins", title: "The Selfish Gene", passage: "Individuals who have too many children are penalized, not because the whole population goes extinct, but simply because fewer of their children survive. Genes for having too many children are just not passed on to the next generation in large numbers, because few of the children bearing these genes reach adulthood. What has happened in modern civilized man is that family sizes are no longer limited by the finite resources that the individual parents can provide. If a husband and wife have more children than they can feed, the state, which means the rest of the population, simply steps in and keeps the surplus children alive and healthy. There is in fact, nothing to stop a couple with no material resources at all having and rearing precisely as many children as the woman can physically bear. But the welfare state is a very unnatural thing. In nature, parents who have more children than they can support do not have many grandchildren, and their genes are not passed on to future generations. There is no need for altruistic restraint in the birth-rate, because there is no welfare state in nature. Any gene for over-indulgence is promptly punished: the children containing that gene starve. Since we humans do not want to return to the old selfish way where we let the children of too-large families starve to death, we have abolished the family as a unit of economic self-sufficiency, and substituted the state. But the privilege of guaranteed support for children should not be abused.
Contraception is sometimes attacked as 'unnatural.' So it is, very unnatural. The trouble is, so is the welfare state. I think that most of us believe the welfare state is highly desirable. But you cannot have an unnatural welfare state, unless you also have unnatural birth control, otherwise the end result will be misery even greater than that which obtains in nature. The welfare state is perhaps the greatest altruistic system the animal kingdom has ever known. But any altruistic system is inherently unstable, because it is open to abuse by selfish individuals, ready to exploit it. Individual humans who have more children than they are capable of rearing are probably too ignorant in most cases to be accused of conscious malevolent exploitation. Powerful institutions and leaders who deliberately encourage them to do so seem to me less free from suspicion.")
  
  b6 = Book.create(cover: "stroud.jpg", author: "Robert Stroud", title: "Looking Outward: A Voice from the Grave", passage: "A common identification made of any boy who had been through this training was the bug scars on his arms or legs, for to inure them to pain, most bum kids, were taught to beg with bugs.
A bug was a lye burn kept open for months and permitted to fester. A paste of wet lye was placed upon a spot about the size of a dollar on the boy's arm or leg, covered with a damp bandage and left on until the skin was destroyed and the member so badly inflamed that it really looked as if the boy had blood poison; then the boy would be sent out to beg, armed with a letter signed by a doctor in some distant town saying that to save the boy's life it would be necessary to amputate the injured arm or leg. There was only one ray of hope, There was just one doctor in America who might be able to save the member and the boy's life, too, but that doctor was always halfway across the Nation. He might be at Mayo's, John Hopkins, or in California, depending on where the boy happened to be. In any case, the boy was begging money to get to the man who could save his arm or leg. He would not go near any local doctor, because he knew the local doctor would want to cut his arm or leg off, and he wasn't going to go through life crippled. If people wanted to help him, all right. If they didn't, he would just go on bumming his way, hoping that he could get to that doctor who could help him in time. If he didn't, well he would probably die in some jungles or boxcar along the way. It was hard to resist such a plea, and a good boy with an active buy was sometimes good for as much as three-hundred dollars per day.
There were cases where boys did lose their arms or legs, and there were cases where the bugs went sour and the boys died, but those where the hazards of life, anyway, so no one paid too much attention to them. In the life these men led, there were many hazards that one could not afford to worry about, but it was a health life; even if most persons would think it a very hard one, man is a rather tough animal, so such cases were much rarer than one would expect. The Writer has seen boys with bugged arms swollen to the shoulder and giving off such a stench of rotting flesh that it was impossible to stay within ten feet of them. Any doctor would say such an arm had to come off at once. But the Writer has seen the same boy three weeks later and heard him moaning because he had not been able to keep his bug active. It had healed in spite of everything he had been able to do to it. Every well-trained yegg had several of these bug scars, and they were, in a way, his diploma.")
  
end